apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: log-all-exec
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    returnArg:
      type: "int"
      index: 0
    selectors:
    - matchActions:
      - action: Post
  - call: "sys_execveat"
    syscall: true
    args:
    - index: 0
      type: "int"
    - index: 1
      type: "string"
    returnArg:
      type: "int"
      index: 0
    selectors:
    - matchActions:
      - action: Post
